# Generated by Django 5.1.1 on 2024-09-27 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.batch",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A_POSITIVE", "A+"),
                    ("A_NEGATIVE", "A-"),
                    ("B_POSITIVE", "B+"),
                    ("B_NEGATIVE", "B-"),
                    ("AB_POSITIVE", "AB+"),
                    ("AB_NEGATIVE", "AB-"),
                    ("O_POSITIVE", "O+"),
                    ("O_NEGATIVE", "O-"),
                ],
                max_length=11,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.course",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.department",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="mobile_no",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
