# Generated by Django 5.1.1 on 2024-10-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_member_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="department",
        ),
        migrations.AlterField(
            model_name="salutation",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name="UserGroup",
        ),
    ]
