# Generated by Django 5.1.1 on 2024-10-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_remove_alumni_counrty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumni",
            name="linked_in",
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="website",
            field=models.URLField(max_length=255),
        ),
    ]
