# Generated by Django 5.1.1 on 2024-10-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_alter_alumni_linked_in_alter_alumni_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumni",
            name="linked_in",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
