# Generated by Django 5.1.1 on 2024-10-14 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_alter_alumni_linked_in_alter_alumni_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member_skills",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="account.member",
            ),
        ),
    ]
