# Generated by Django 5.1.1 on 2024-10-08 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0008_alter_alumni_linked_in_alter_alumni_website"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("total_years_of_experience", models.FloatField()),
                ("resume", models.FileField(upload_to="resumes/")),
                ("notes_to_recruiter", models.TextField(blank=True, null=True)),
                ("applied_on", models.DateField(auto_now_add=True)),
                (
                    "current_industry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_industry",
                        to="account.industry",
                    ),
                ),
                (
                    "current_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_role",
                        to="account.role",
                    ),
                ),
                ("skills", models.ManyToManyField(to="account.skill")),
            ],
        ),
        migrations.CreateModel(
            name="BusinessDirectory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("website", models.URLField(blank=True, max_length=255, null=True)),
                ("location", models.CharField(max_length=255)),
                ("contact_email", models.EmailField(max_length=255)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("are_you_part_of_management", models.BooleanField(default=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("listed_on", models.DateField(auto_now_add=True)),
                (
                    "country_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.country",
                    ),
                ),
                (
                    "industry_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.industry_type",
                    ),
                ),
                (
                    "listed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=255)),
                ("experience_level_from", models.IntegerField()),
                ("experience_level_to", models.IntegerField()),
                ("location", models.CharField(max_length=255)),
                ("contact_email", models.EmailField(max_length=255)),
                (
                    "contact_link",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                (
                    "salary_package",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("dead_line", models.DateField()),
                ("job_description", models.TextField()),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="job_files/"),
                ),
                (
                    "post_type",
                    models.CharField(
                        choices=[("Job", "Job"), ("Internship", "Internship")],
                        max_length=225,
                    ),
                ),
                ("posted_on", models.DateField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "industry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.industry",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.role"
                    ),
                ),
                ("skills", models.ManyToManyField(to="account.skill")),
            ],
        ),
        migrations.CreateModel(
            name="JobComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "comment_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job_portal.jobpost",
                    ),
                ),
            ],
        ),
    ]
